server:
  port: 2000
user-service:
  port: 2002

spring:
  cache:
    cache-names: user
  cloud:
    bus:
      trace:
        enabled: true
      destination: 'coucous_les_zouzous'
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
